# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 02:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 10, 28, 2, 30, 1, 371025, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
